version: 2
registries:
  terraform:
    type: terraform-registry
    url: https://app.terraform.io
    token: ${{secrets.MY_TERRAFORM_API_TOKEN}}

updates:
  - package-ecosystem: "terraform" 
    directory: "/" 
    registries: "*"
    commit-message:
      prefix: "[dependabot]"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
