# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  terraform:
    type: terraform-registry
    url: https://app.terraform.io
    token: ${{secrets.MY_TERRAFORM_API_TOKEN}}

updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries: "*"
    commit-message:
      prefix: "[dependabot]"
    open-pull-requests-limit: 20
    schedule:
      interval: "cron"
      cronjob: "0 17 * * *" # daily at 1:00pm Eastern Time US (ET is UTC-4 during daylight saving)
